a=0; a++;window['q'+a] = "One Piece";
a++;window['q'+a] = "Vinland Saga";
a++;window['q'+a] = "Demon Slayer";
a++;window['q'+a] = "Boruto";
a++;window['q'+a] = "Naruto";
a++;window['q'+a] = "Chainsaw Man";
a++;window['q'+a] = "Jujutsu Kaisen";
a++;window['q'+a] = "Tokyo Revengers";
a++;window['q'+a] = "Hunter x Hunter";
a++;window['q'+a] = "Black Clover";
a++;window['q'+a] = "JoJo's Bizarre Adventure";
a++;window['q'+a] = "Fullmetal Alchemist";
a++;window['q'+a] = "Cyberpunk";
a++;window['q'+a] = "One Punch Man";
a++;window['q'+a] = "Bleach";
a++;window['q'+a] = "Dragon Ball Z";
a++;window['q'+a] = "Berserk";
a++;window['q'+a] = "Cowboy Bebop";
a++;window['q'+a] = "Neon Genesis Evangelion";
a++;window['q'+a] = "Mob Psycho 100";
a++;window['q'+a] = "Code Geass";
a++;window['q'+a] = "Steins Gate";
a++;window['q'+a] = "My Dress Up Darling";
a++;window['q'+a] = "The Seven Deadly Sins";
a++;window['q'+a] = "Record of Ragnarok";
a++;window['q'+a] = "Sword Art Online";
a++;window['q'+a] = "Fruits Basket";
a++;window['q'+a] = "The Promised Neverland";
a++;window['q'+a] = "High School DxD";
a++;window['q'+a] = "Fire Force";
a++;window['q'+a] = "Ranking of Kings";
a++;window['q'+a] = "The Rising of the Shield Hero";
a++;window['q'+a] = "Darling in the Franxx";


levelTotal = a;